name: Complex Workflow

on: push

jobs:
  job-ubuntu:
    runs-on: ubuntu-latest

    steps:
      - run: date

  job-windows:
    runs-on: windows-latest

    steps:
      - run:  echo %date%-%time%

  job-mac:
    needs: [job-ubuntu, job-windows]
    runs-on: macos-latest

    steps:
      - run: date

  job-dependant:
    needs: [job-ubuntu, job-windows, job-mac]

    runs-on: ubuntu-latest

    steps:
      - run: date